# Meta Data for SEO

## Homepage
title = "Lokerku"
titleSeparator = "-"
titleAddition = "Mari Cari Lowongan Pekerjaan Bersamaku Kawan"
description = "Mari Cari Lowongan Pekerjaan Bersamaku Kawan" 
## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "/"
titleHome = "Lokerku"

## Twitter Cards
twitterSite = "@getdoks"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/getdoks"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/doks"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "360"

# Footer
footer = "Build with 💤 <a href="\"> Hugo</a>
copyRight = "Copyright (c) 2021"

# Alert
alert = false
alertDismissable = false
# alertText = "Help Doks grow by supporting us on Open Collective. <a class=\"alert-link stretched-link\" href=\"https://opencollective.com/doks\" target=\"_blank\" rel=\"noopener\">Become a backer!</a>"
alertText = "Better UX navigation, multilingual and i18n support, and more. <a class=\"alert-link stretched-link\" href=\"/blog/doks-v0.3/\">Check out what's new!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/getdoks.org"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  darkMode = true
  bootStrapJs = true
  highLight = true
  collapsibleSidebar = true
  multilingualMode = false # Not yet functional
  docsVersioning = false # Not yet functional
